name: ci
on: push

jobs:
  test-split:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Print GitHub variables 🖨
        run: npx @bahmutov/print-env GITHUB

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Run Cypress Tests Split
        uses: cypress-io/github-action@v6

        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{strategy.job-index}}
